### ISSUE TITLE
Cursor set to "pointer" when disabled

### ISSUE THREAD

**Issue by jarrodek** [salte-io/salte-rating#13]
When the component is disable it still renders cursor as "pointer".

Proper way of styling using `:host` is:

```css
:host([disabled]) .foreground-rating .item {
  cursor: default;
}
```

Also the value here should be "inherit" as an author using the component can set different cursor for any reason.
